// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@3.0.4";

// src/lib/mcp/tools/list-analysis-sessions.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@3.0.4";
import { z } from "npm:zod@^4.6.5";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv(["SUPABASE_PUBLISHABLE_KEY", "VITE_SUPABASE_PUBLISHABLE_KEY"]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("Supabase publishable key is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function unauthenticated() {
  return {
    content: [{ type: "text", text: "Not authenticated. Sign in to this app to use these tools." }],
    isError: true
  };
}

// src/lib/mcp/tools/list-analysis-sessions.ts
var list_analysis_sessions_default = defineTool({
  name: "list_analysis_sessions",
  title: "List analysis sessions",
  description: "List the signed-in user's saved sentiment analysis sessions with summary metrics (source, totals, sentiment distribution).",
  inputSchema: {
    limit: z.number().int().min(1).max(50).optional().describe("Maximum number of sessions to return (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const { data, error } = await supabaseForUser(ctx).from("analysis_sessions").select("id, title, source_type, source_url, total_analyzed, average_confidence, distribution, created_at").order("created_at", { ascending: false }).limit(limit ?? 10);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { sessions: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-analysis-session.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@3.0.4";
import { z as z2 } from "npm:zod@^4.6.5";
var get_analysis_session_default = defineTool2({
  name: "get_analysis_session",
  title: "Get analysis session",
  description: "Get the full detail of one saved sentiment analysis session, including aspect summary, top keywords and per-review predictions.",
  inputSchema: {
    id: z2.string().uuid().describe("The analysis session id returned by list_analysis_sessions."),
    include_predictions: z2.boolean().optional().describe("Include the per-review predictions array (can be large). Default false.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id, include_predictions }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const { data, error } = await supabaseForUser(ctx).from("analysis_sessions").select("*").eq("id", id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "No analysis session found with that id." }], isError: true };
    const { predictions, ...rest } = data;
    const session = include_predictions ? { ...rest, predictions } : rest;
    return {
      content: [{ type: "text", text: JSON.stringify(session, null, 2) }]
    };
  }
});

// src/lib/mcp/tools/delete-analysis-session.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@3.0.4";
import { z as z3 } from "npm:zod@^4.6.5";
var delete_analysis_session_default = defineTool3({
  name: "delete_analysis_session",
  title: "Delete analysis session",
  description: "Permanently delete one of the signed-in user's saved sentiment analysis sessions.",
  inputSchema: {
    id: z3.string().uuid().describe("The analysis session id to delete.")
  },
  annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const { error } = await supabaseForUser(ctx).from("analysis_sessions").delete().eq("id", id);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Deleted analysis session ${id}.` }],
      structuredContent: { deleted: id }
    };
  }
});

// src/lib/mcp/tools/analyze-reviews.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@3.0.4";
import { z as z4 } from "npm:zod@^4.6.5";
var analyze_reviews_default = defineTool4({
  name: "analyze_reviews",
  title: "Analyze reviews",
  description: "Run aspect-based sentiment analysis on up to 40 review texts and save the result to the signed-in user's history. Returns sentiment distribution, aspect summary, top keywords and average confidence.",
  inputSchema: {
    reviews: z4.array(z4.string().min(1)).min(1).max(40).describe("Review texts to analyze."),
    title: z4.string().optional().describe("Optional label for the saved analysis session.")
  },
  annotations: { readOnlyHint: false, openWorldHint: true },
  handler: async ({ reviews, title }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const baseUrl = supabaseProjectUrl();
    const anonKey = supabasePublishableKey();
    const res = await fetch(`${baseUrl}/functions/v1/analyze-sentiment`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        apikey: anonKey,
        Authorization: `Bearer ${ctx.getToken()}`
      },
      body: JSON.stringify({ reviews })
    });
    const data = await res.json().catch(() => null);
    if (!res.ok || !data?.success) {
      return {
        content: [{ type: "text", text: data?.error ?? `Analysis failed with status ${res.status}.` }],
        isError: true
      };
    }
    const summary = {
      totalAnalyzed: data.totalAnalyzed,
      averageConfidence: data.averageConfidence,
      distribution: data.distribution,
      aspectSummary: data.aspectSummary,
      wordFrequencies: data.wordFrequencies
    };
    const { data: inserted } = await supabaseForUser(ctx).from("analysis_sessions").insert({
      user_id: ctx.getUserId(),
      source_type: "mcp",
      title: title ?? `MCP analysis (${reviews.length} reviews)`,
      total_analyzed: data.totalAnalyzed,
      average_confidence: data.averageConfidence,
      distribution: data.distribution,
      aspect_summary: data.aspectSummary,
      word_frequencies: data.wordFrequencies,
      predictions: data.predictions
    }).select("id").maybeSingle();
    return {
      content: [{ type: "text", text: JSON.stringify({ ...summary, sessionId: inserted?.id ?? null }, null, 2) }],
      structuredContent: { ...summary, sessionId: inserted?.id ?? null }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "xpmmkmtzczerwrlbprcf";
var mcp_default = defineMcp({
  name: "review-insights-dashboard",
  title: "Review Insights Dashboard",
  version: "0.1.0",
  instructions: "Aspect-based sentiment analysis of product reviews. Use `analyze_reviews` to analyze review texts, `list_analysis_sessions` / `get_analysis_session` to browse saved results, and `delete_analysis_session` to remove one.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_analysis_sessions_default, get_analysis_session_default, delete_analysis_session_default, analyze_reviews_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@3.0.4/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
